### ISSUE TITLE
package couldn't compile

### ISSUE THREAD

**Issue by kaka21garuda** [vapor/mysql-provider#19]
when I added `.Package(url: "https://github.com/vapor/mysql-provider.git", majorVersion: 1, minor: 0)` and do `vapor clean` `vapor Xcode -y`, I still can't import VaporMySQL as my module. Also I kept on getting these 2 errors, 

> **Header '/usr/local/include/mysql/mysql.h' not found**

> **Could not build Objective-C module 'CMySQLMac'**

I have also a running MySQL server running on my machine.

**Comment by benjdum59** [comment]
How did you install MySQL? Homebrew or an official installation?

**Comment by kaka21garuda** [comment]
@benjdum59 brew install MySQL.
