### ISSUE TITLE
MySQL - not showing as an Import value

### ISSUE THREAD

**Issue by rustymagnet3000** [vapor/mysql-provider#2]
Did anybody else experience the same issue?  I fear it may be my lack of knowledge/skill with Swift's Package Manager and versions...

http://stackoverflow.com/questions/38544089/vapor-mysql-not-showing-as-an-import-value

**Comment by kaka21garuda** [comment]
@rustymagnet3000 yes I am currently having the same issue, but apparently they had changed the package dependency link to:
`.Package(url: "https://github.com/vapor/mysql-provider.git", majorVersion: 1, minor: 0)`.
Make sure you have a MySQL server running locally in your machine too.
