### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by ghost** [vapor/mysql-provider#35]
![image](https://user-images.githubusercontent.com/12078861/28996352-5a4de8a8-7a31-11e7-85f7-0d69a685fc48.png)
After I added denpendencies
`.Package(url: "https://github.com/vapor/mysql-provider.git", majorVersion: 2)`
My project can not be built by xcode.
Then I use 
`vapor build`
the terminal give tips to use
`brew install cmysql`
then i can build this project by vapor toobox.
I openned my xcode again.This error is still exist.
When  i openned my denpendencies folder.
![image](https://user-images.githubusercontent.com/12078861/28996385-23d1279e-7a32-11e7-81a7-830af44fb78c.png)
I found nothing in CMySQL folder.
THX!

**Comment by 0xTim** [comment]
Did you try building after running `brew install cmysql`?

IIRC it is just a module map so you probably won't see any code anyway

**Comment by tanner0101** [comment]
Make sure to re-generate your Xcode project after doing `brew install vapor/tap/cmysql`.
